apiVersion: v1
kind: ReplicationController
metadata:
  name: pod-python
spec:
  replicas: 2
  selector:
    app: pod-python
  template:
    metadata:
      labels:
        app: pod-python
    spec:
      containers:
      - name: ubuntu-python
        image: doublev20/valentin:version3
        ports:
        - containerPort: 8080
