apiVersion: v1
kind: Pod
metadata:
  name: pod-python
  namespace: pod-test
spec:
  selector:
    app: pod-python
  containers:
  - name: ubuntu-python
    image: doublev20/valentin:version3
    ports:
    - containerPort: 8080
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    
